# Generated by Django 5.0.6 on 2024-05-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cuit',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dni_cuit',
            field=models.CharField(default='00000000000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_factura',
            field=models.CharField(default='X', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.venta'),
        ),
        migrations.DeleteModel(
            name='Comprobante',
        ),
    ]
